name: Compile ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install ESPHome
        run: |
          pip install esphome

      - name: Compile MQTT Binary
        # 请确保下面的 my_esp32.yaml 对应你仓库里的文件名
        run: esphome compile my_esp32.yaml

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: esphome-binaries
          # 编译后的文件通常在 .esphome/build/设备名/.pioenvs/设备名/firmware.factory.bin
          # 我们直接打包整个 build 文件夹下的 bin
          path: .esphome/build/*/.*.bin
