name: Compile ESPHome S3

on:
  workflow_dispatch: # 允许你手动点击 "Run workflow" 触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ESPHome
        run: |
          pip install esphome
          esphome version

      - name: Compile Binary
        run: esphome compile air-quality-pms5003s.yaml

      - name: List files (Debug)
        # 这一步会列出当前目录下所有 bin 文件，帮我们确认位置
        run: find . -name "*.bin"

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: pms5003s-firmware
          # 直接定位到具体目录，避免通配符歧义
          path: .esphome/build/air-quality-pms5003s/.pioenvs/air-quality-pms5003s/firmware.factory.bin
          # 关键点：强制要求上传包含隐藏路径的文件
          include-hidden-files: true
          if-no-files-found: error
